### ISSUE TITLE
opt.load_baseg

### ISSUE THREAD

**Issue by CVStack** [zengxianyu/crfill#12]
In the second train.py "update_part=fine" of train.sh, I got the error about opt.load_baseg in the util.py.

![image](https://user-images.githubusercontent.com/38209962/142433400-2045775a-1c5e-42d6-a21d-c02340d09337.png)

I thought there isn't the part for adding load_baseg arguments in the train_options, So, I add it as test_options.

is it right for training?

**Comment by zengxianyu** [comment]
It’s supposed to be in the train_options

**Comment by CVStack** [comment]
Okay! Thank you :)
