### ISSUE TITLE
Changing masks generated in training data

### ISSUE THREAD

**Issue by AhmedHashish123** [zengxianyu/crfill#15]
Hello, thank you for your interesting work. I was wondering where you generate masks for the training data images. Because I wanted to know if I could change the method of generation of these masks to make them not be generated randomly in any part of the training images.

**Comment by zengxianyu** [comment]
https://github.com/zengxianyu/crfill/blob/9758f265bad6c55459aab173ffee5f07f5e44c20/models/inpaint_model.py#L122

**Comment by AhmedHashish123** [comment]
@zengxianyu thank you.
