### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ishaybeyondminds** [zengxianyu/crfill#4]
do you intend to publish training code any time soon?

**Comment by zengxianyu** [comment]
I will publish the training code after the paper is accepted

**Comment by ishaybeyondminds** [comment]
thanks. do you know when it will happend?

**Comment by zengxianyu** [comment]
Sorry I don't know



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月18日(星期天) 下午3:36
收件人: ***@***.***&gt;; 
抄送: "Yu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zengxianyu/crfill] training code (#4)





 
thanks. do you know when it will happend?

**Comment by ishaybeyondminds** [comment]
Ok. Thanks I will stay tuned.

**Comment by roimulia2** [comment]
Waiting as well :)

**Comment by ofirkris** [comment]
Waiting as well :)

**Comment by sysuzyq** [comment]
Waiting as well :)

**Comment by Sara-Sheykh** [comment]
Hey do share the training code and weights for discriminator please. Amazing work done there!

**Comment by chaowentao** [comment]
Your model's result is amazing! I want to train my own data. Please share the training code.

**Comment by zengxianyu** [comment]
the training code is released
